name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Test
    runs-on: Ubuntu-20.04
    steps:
      - uses: denolib/setup-deno@v2
        with:
          deno-version: 2.x
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            .yarn/cache
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: Fetch dependencies
        run: yarn --immutable
      - name: Test
        run: yarn test
